// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaCumTte6fcnRTUvNt2DVZ-pN5gWY-o10',
    appId: '1:807564432883:web:c71a3c4f64c73f087eee86',
    messagingSenderId: '807564432883',
    projectId: 'fir-two-89ada',
    authDomain: 'fir-two-89ada.firebaseapp.com',
    storageBucket: 'fir-two-89ada.appspot.com',
    measurementId: 'G-PBM27CVJ6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-lDsv5S4xhCySX9-JEpGB_5NjPkt0-Bs',
    appId: '1:807564432883:android:5398296941315e8f7eee86',
    messagingSenderId: '807564432883',
    projectId: 'fir-two-89ada',
    storageBucket: 'fir-two-89ada.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfC3FJ-DyFBnATyeIKLNYxjpQJrA6nLAw',
    appId: '1:807564432883:ios:be8b9cd848460da07eee86',
    messagingSenderId: '807564432883',
    projectId: 'fir-two-89ada',
    storageBucket: 'fir-two-89ada.appspot.com',
    iosBundleId: 'com.example.firebasetwo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfC3FJ-DyFBnATyeIKLNYxjpQJrA6nLAw',
    appId: '1:807564432883:ios:be8b9cd848460da07eee86',
    messagingSenderId: '807564432883',
    projectId: 'fir-two-89ada',
    storageBucket: 'fir-two-89ada.appspot.com',
    iosBundleId: 'com.example.firebasetwo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaCumTte6fcnRTUvNt2DVZ-pN5gWY-o10',
    appId: '1:807564432883:web:1b9e37e4de2c5d317eee86',
    messagingSenderId: '807564432883',
    projectId: 'fir-two-89ada',
    authDomain: 'fir-two-89ada.firebaseapp.com',
    storageBucket: 'fir-two-89ada.appspot.com',
    measurementId: 'G-958Q3VQ00G',
  );
}
